#!/usr/bin/env bash
# prints "best school" ten times
for i in "Best School" "Best School" "Best School"\
 "Best School" "Best School" "Best School"\
 "Best School" "Best School" "Best School" "Best School";
    do echo "$i";
done
